# Generated by Django 3.2.7 on 2021-12-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_content_message_text_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text_content',
            new_name='content',
        ),
    ]
