# Generated by Django 3.2.7 on 2022-01-12 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_rename_text_content_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.ManyToManyField(related_name='viewed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
