# Generated by Django 3.2.7 on 2022-01-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20220112_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='read_by',
        ),
    ]
