# Generated by Django 3.2.7 on 2022-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
