# Generated by Django 4.0.1 on 2022-01-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_files_message_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attached_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='files'),
        ),
    ]
