# Generated by Django 3.2.3 on 2021-08-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='creator',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='date',
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='data_of_birth',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
