# Generated by Django 3.2.3 on 2021-08-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0002_auto_20210808_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('NS', 'not specified')], default='NS', max_length=2),
        ),
    ]
