# Generated by Django 3.2.3 on 2021-08-13 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dosti', '0004_alter_friendship_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friends',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
