# Generated by Django 3.2.3 on 2021-08-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0006_friendrequests_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
