# Generated by Django 3.2.3 on 2021-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0007_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='conver_photo',
            field=models.CharField(default='cp1.jpg', max_length=255),
        ),
    ]
