# Generated by Django 3.2.3 on 2021-08-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0008_userprofilemodel_conver_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='conver_photo',
            new_name='cover_photo',
        ),
    ]
