# Generated by Django 3.2.3 on 2021-09-06 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dosti', '0009_rename_conver_photo_userprofilemodel_cover_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileModel',
            new_name='UserProfile',
        ),
    ]
