# Generated by Django 3.2.3 on 2021-09-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0010_rename_userprofilemodel_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='kabul', max_length=55),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='afghanistan', max_length=55),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workplace',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
