# Generated by Django 3.2.3 on 2021-09-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0011_auto_20210906_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
