# Generated by Django 3.2.3 on 2021-09-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0012_rename_data_of_birth_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequests',
            old_name='timestamp',
            new_name='time_stamp',
        ),
    ]
