# Generated by Django 3.2.3 on 2021-09-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0014_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
