# Generated by Django 3.2.3 on 2021-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0015_remove_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='Love humanity :)', max_length=255),
        ),
    ]
