# Generated by Django 3.2.3 on 2021-09-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0016_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='martial_state',
            field=models.CharField(choices=[('S', 'single'), ('M', 'maried'), ('E', 'engaged')], default='S', max_length=1),
        ),
    ]
