# Generated by Django 3.2.3 on 2021-09-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0017_userprofile_martial_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='martial_state',
            new_name='marital_state',
        ),
    ]
