# Generated by Django 3.2.3 on 2021-09-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0018_rename_martial_state_userprofile_marital_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
