# Generated by Django 3.2.3 on 2021-09-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0020_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
