# Generated by Django 3.2.3 on 2021-09-24 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0021_remove_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.date(2001, 12, 18)),
        ),
    ]
