# Generated by Django 4.0.1 on 2022-01-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosti', '0029_auto_20211213_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='coverPhotos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profilesPics'),
        ),
    ]
